language: c

os:
 - linux
 - osx

compiler:
 - clang
 - gcc

env:
 - CONFIG_OPTS=""
 - CONFIG_OPTS="--debug"
 - CONFIG_OPTS="shared"

script:
 - ./config $CONFIG_OPTS && make && make test

notifications:
  recipient:
   - openssl-dev@openssl.org
  email:
    on_success: change
    on_failure: always
